### PR TITLE
Close all Unix abstract sockets correctly

### LINKED ISSUE #409: Stop VM returns before the VM is terminated completely
When I repeatedly start and stop a VM with the same vmID, I get `AlreadyExists` error after StopVM returned.

To reproduce:
```
cd REPO_ROOT/examples
sudo make test tap
while true; do sudo ./taskworkflow -ip 172.16.0.2/24     -gw 172.16.0.1; done
```
Error:
```
<p><em>Thank you for using nginx.</em></p>
</body>
</html>
]
172.16.0.1 - - [17/Apr/2020:12:28:43 +0000] "GET / HTTP/1.1" 200 612 "-" "Go-http-client/1.1" "-"
2020/04/17 14:28:43.873658 task exited with status: 0
2020/04/17 14:28:49.338855 Creating containerd client
2020/04/17 14:28:49.339348 Created containerd client
2020/04/17 14:28:50.430147 failed to create VM: rpc error: code = AlreadyExists desc = VM with ID "fc-example" already exists
2020/04/17 14:28:50.455760 Creating containerd client
2020/04/17 14:28:50.456200 Created containerd client
2020/04/17 14:28:51.473040 failed to create VM: rpc error: code = AlreadyExists desc = VM with ID "fc-example" already exists
<........>
2020/04/17 14:29:00.082014 Creating containerd client
2020/04/17 14:29:00.082454 Created containerd client
2020/04/17 14:29:02.502417 Successfully pulled docker.io/library/nginx:1.17-alpine image with devmapper
2020/04/17 14:29:02.909850 Successfully created task: demo for the container

```

Also, StopVM indicates errors in the log. 

```
DEBU[2020-04-17T14:27:14.211781422+02:00] stop VM: VMID:"fc-example"                   
INFO[2020-04-17T14:27:14.212062270+02:00] stopping the VM                               runtime=aws.firecracker vmID=fc-example
ERRO[2020-04-17T14:27:14.212487793+02:00] error while forwarding events from VM agent   error="rpc error: code = Canceled desc = context canceled" runtime=aws.firecracker vmID=fc-example
DEBU[2020-04-17T14:27:14.224225467+02:00] schedule snapshotter cleanup                  snapshotter=devmapper
DEBU[2020-04-17T14:27:14.224272656+02:00] walk                                         
DEBU[2020-04-17T14:27:14.224333853+02:00] remove                                        key=firecracker-containerd-example/5/demo-snapshot
DEBU[2020-04-17T14:27:14.325948982+02:00] removed snapshot                              key=firecracker-containerd-example/5/demo-snapshot snapshotter=devmapper
DEBU[2020-04-17T14:27:14.325985595+02:00] snapshot garbage collected                    d=101.719977ms snapshotter=devmapper
DEBU[2020-04-17T14:27:14.326017003+02:00] garbage collected                             d="418.806µs"
INFO[2020-04-17T14:27:14.569484082+02:00] firecracker exited: status=0                  runtime=aws.firecracker vmID=fc-example
ERRO[2020-04-17T14:27:14.569709040+02:00] failed to stop vm "fc-example"                error="os: process already finished" runtime=aws.firecracker vmID=fc-example
DEBU[2020-04-17T14:27:14.570022526+02:00] event forwarded                               ns=firecracker-containerd-example topic=/firecracker-vm/stop type=VMStop
```

Is it a bug in the example or in firecracker-containerd?

### PR DESCRIPTION
**Pull request by kzys**
*Issue #, if available:*

#409

*Description of changes:*

We were not closing Unix abstract sockets on firecracker-local side,
which keeps the sockets alive. Clients cloud not create a new VM with
exact same identity.

In addition to that, firecracker-local now gurantees the absence of
a shim process, to make StopVM's contracts clear.

Fixes #409.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: runtime/service_integ_test.go [hunk 1]
```diff
@@ -583,7 +583,7 @@ func TestLongUnixSocketPath_Isolated(t *testing.T) {
 	// default location we store state results in a path like
 	// "/run/firecracker-containerd/default/<vmID>" (with len 112).
 	const maxUnixSockLen = 108
-	vmID := strings.Repeat("x", 72)
+	vmID := strings.Repeat("x", 76)
```
Comment (IRCody) [inline runtime/service_integ_test.go:586]: why 76?

File: firecracker-control/local.go [hunk 2]
```diff
@@ -47,6 +50,7 @@ import (
 var (
 	_               fccontrolTtrpc.FirecrackerService = (*local)(nil)
 	ttrpcAddressEnv                                   = "TTRPC_ADDRESS"
+	stopVMInterval                                    = 10 * time.Millisecond
```
Comment (IRCody) [inline firecracker-control/local.go:53]: why is this reasonable?

File: runtime/service_integ_test.go (hunk 1 above)
Comment (kzys) [reply runtime/service_integ_test.go:586]: That's the original number before my change (#414). It could be shorter though.

File: firecracker-control/local.go (hunk 2 above)
Comment (kzys) [reply firecracker-control/local.go:53]: No strong reason regarding the number. Do you think it is too frequent?

Comment (IRCody) [reply firecracker-control/local.go:53]: We talked offline. Summary is that since the process will be SIGKILL if it doesn't exit cleanly this is ok since the time we will be checking for is relatively short.
