### PR TITLE
Forward agent containerd events to shim and monitor task exits via event subscriptions

### LINKED ISSUE #87: killing task doesn't work properly
the kill task doesn't work properly and causes shim zombie issue 
pls let me know if you need any extra info
```
ctr c create --snapshotter firecracker-dm-snapshotter --runtime aws.firecracker docker.io/library/redis:latest myredis1
ctr tasks start myredis1
```
```
1:C 06 Feb 2019 19:11:45.423 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Feb 2019 19:11:45.423 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 06 Feb 2019 19:11:45.423 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 06 Feb 2019 19:11:45.425 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
1:M 06 Feb 2019 19:11:45.426 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
1:M 06 Feb 2019 19:11:45.426 # Current maximum open files is 1024. maxclients has been reduced to 992 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
1:M 06 Feb 2019 19:11:45.428 * Running mode=standalone, port=6379.
1:M 06 Feb 2019 19:11:45.428 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 06 Feb 2019 19:11:45.428 # Server initialized
1:M 06 Feb 2019 19:11:45.428 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 06 Feb 2019 19:11:45.429 * Ready to accept connections
```
```
ctr tasks list
TASK        PID    STATUS    
myredis1    996    RUNNING
ctr tasks kill myredis1
```
```
1:signal-handler (1549480354) Received SIGTERM scheduling shutdown...
ctr: rpc error: code = Unknown desc = ttrpc: client shutting down: read vsock:host(2):1028: connection reset by peer: unknown
```
```
ps axu | grep shim
root      4016  0.4  0.0 784440 13444 pts/0    Sl   19:11   0:01 /usr/local/bin/containerd-shim-aws-firecracker -namespace default -address /run/containerd/containerd.sock -publish-binary /usr/local/bin/containerd
```
```
ctr tasks ls
ERRO[2019-02-06T19:17:25.961348016Z] converting task to protobuf                   error="ttrpc: client shutting down: read vsock:host(2):1028: connection reset by peer: unknown" id=myredis1
TASK    PID    STATUS    
```

### PR DESCRIPTION
**Pull request by sipsma**
Fixes #87 

More details in full commit messages, but overall goal of the change is to forward all containerd events from the agent to the shim on the host and then use that to monitor task exits, at which time we can gracefully shut everything down.

Sending this out to get feedback on the implementation right away, but I won't merge until I've also written an integration test (which is likely going to entail addressing #114) and added unit tests for the new EventExchange code. That being said, the testing done so far has been manual. I verified that both killing a task (via `ctr kill`) and the task exiting on its own result in a task exit event being forwarded to and logged by containerd. The shim and VM exit as expected in both cases too.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sipsma** [comment]
I forgot to run the linter locally before pushing, will fix that before merging

File: exchangeBridge/exchange.go [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+			} else {
+				return nil
+			}
+		default:
+		}
+
+		envelope, err := exchangeBridge.GetEvent(ctx)
+		if err != nil {
+			return err
+		}
```
Comment (mxpv) [inline exchangeBridge/exchange.go]: What happens if there are no new events published? Will it fail here with timeout and will stop pulling events?

File: exchangeBridge/exchange.go [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+
+	select {
+	case receivedEnvelope := <-s.eventChan:
+		envelope = &eventapi.Envelope{
+			Timestamp: receivedEnvelope.Timestamp,
+			Namespace: receivedEnvelope.Namespace,
+			Topic:     receivedEnvelope.Topic,
+			Event:     receivedEnvelope.Event,
+		}
+	case err = <-s.errChan:
```
Comment (mxpv) [inline exchangeBridge/exchange.go]: should we return here?

File: exchangeBridge/exchange.go [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+func AttachExchangeBridge(ctx context.Context, exchangeBridge ExchangeBridge, forwarder events.Forwarder) error {
+	for {
+		select {
+		case <-ctx.Done():
+			if ctxErr := ctx.Err(); ctxErr != context.Canceled {
+				return ctxErr
+			} else {
+				return nil
+			}
+		default:
```
Comment (mxpv) [inline exchangeBridge/exchange.go]: Do we need empty default here? Without `default` "select" statement just blocks until ctx.Done can proceed

File: exchangeBridge/exchange.go (hunk 2 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: We don't need to as we will return the err below. The implementation here works as is but I agree it's kind of a different approach than what I did elsewhere, so I can update this to just return in each select case for the sake of consistency.

File: exchangeBridge/exchange.go (hunk 3 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: We want the empty default so we don't get blocked on the call to ctx.Done(). The select here is just a check to see if the context was canceled already, at which point we can return from this function. If the context wasn't canceled, we want to continue on with the loop.

File: exchangeBridge/exchange.go (hunk 1 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: Looking through the TTRPC codebase I wasn't able to find any implementation of timeouts, so as far as I can tell the request will just block indefinitely until events are available or the connection is closed by either side. I also manually let a container sit around for 10 minutes and verified the task exit event was still propagated as expected afterwards (admittedly not the most robust test, but not sure how else to verify at this moment).

Let me know if I'm missing something.

File: exchangeBridge/exchange.go (hunk 3 above)
Comment (mxpv) [reply exchangeBridge/exchange.go]: Ah. I get it the idea. I thought this is a cycle :( I would rather suggest something like this instead:
```
if _, ok := <- ctx.Done(); ok {
			
}
```

File: exchangeBridge/exchange.go (hunk 1 above)
Comment (mxpv) [reply exchangeBridge/exchange.go]: Yep. Timeouts are not yet implemented https://github.com/containerd/ttrpc/issues/3

File: exchangeBridge/exchange.go (hunk 2 above)
Comment (mxpv) [reply exchangeBridge/exchange.go]: I prefer to return as early as possible. This makes reading code a bit easier.

File: exchangeBridge/exchange.go (hunk 3 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: I completely forgot you could do that to implement a non-blocking read from a channel. Agree it's more readable, will update the PR

File: exchangeBridge/exchange.go (hunk 1 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: Thanks, that's good to know! Hopefully they add support for timeouts in a backwards-compatible way, but I'll assume they won't and see what I can do to cover this when adding tests (maybe just have a container sit around for 30ish seconds before existing or something like that).

File: exchangeBridge/exchange.go (hunk 3 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: Apparently that syntax actually is still blocking: https://play.golang.org/p/ccsYmAn4BTf

So I'll leave it as is but add a command above the select clarifying what it's doing

File: exchangeBridge/exchange.go [hunk 4]
```diff
@@ -0,0 +1,161 @@
...
+	ExchangeBridgeServiceName = "aws.firecracker.containerd.exchangeBridge"
+	GetEventMethodName = "GetEvent"
+)
+
+// The ExchangeBridge interface provides an API for retrieving containerd events from a remote event exchange. It exists
+// separately from containerd's existing EventClient and EventServer interfaces in order to support retrieving events
+// via long-polling as opposed to a streaming model. This allows us to use TTRPC for the implementation, which currently
+// does not support streaming.
+type ExchangeBridge interface {
+	GetEvent(ctx context.Context) (*eventapi.Envelope, error)
```
Comment (samuelkarp) [inline exchangeBridge/exchange.go]: Can you add godoc for `GetEvent`?

File: exchangeBridge/exchange.go [hunk 5]
```diff
@@ -0,0 +1,161 @@
...
+// in the subscription's channel of published events.
+func NewExchangeBridgeService(ctx context.Context, eventSource events.Subscriber) ExchangeBridge {
+	eventChan, errChan := eventSource.Subscribe(ctx)
+	return &exchangeBridgeService{
+		eventChan: eventChan,
+		errChan:   errChan,
+	}
+}
+
+func RegisterExchangeBridgeService(srv *ttrpc.Server, svc ExchangeBridge) {
```
Comment (samuelkarp) [inline exchangeBridge/exchange.go]: This needs some godoc as well.

File: exchangeBridge/exchange.go (hunk 2 above)
Comment (samuelkarp) [reply exchangeBridge/exchange.go]: I'd encourage returning at the site of an error.  It's easy to miss that the error is supposed to be returned when we come back and edit this code later if it's only returned at the bottom of the function.  I'd also encourage returning `nil, err` so that we explicitly have no `eventapi.Envelope` instead of one that may be invalid.

File: exchangeBridge/exchange.go [hunk 6]
```diff
@@ -0,0 +1,161 @@
+package exchangeBridge
```
[the remark this answers is not in the document]
Comment (xibz) [reply exchangeBridge/exchange.go]: And further, the folder name shouldn't be camel cased either. I think calling the folder `exchange` and the package `exchange` would be my preference.

File: exchangeBridge/exchange.go [hunk 7]
```diff
@@ -0,0 +1,161 @@
...
+	rpcClient *ttrpc.Client
+}
+
+func NewExchangeBridgeClient(rpcClient *ttrpc.Client) ExchangeBridge {
+	return &exchangeBridgeClient{
+		rpcClient: rpcClient,
+	}
+}
+
+func (c *exchangeBridgeClient) GetEvent(ctx context.Context) (*eventapi.Envelope, error) {
```
Comment (xibz) [inline exchangeBridge/exchange.go]: Can we get a description on how this method work in getting an event?

File: exchangeBridge/exchange.go (hunk 5 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: This one I felt at the time was self-explanatory, but in retrospect it doesn't hurt to explain that it must be called to add the method to the provided server, will do.

File: exchangeBridge/exchange.go (hunk 2 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: Yeah that makes total sense, will update

File: exchangeBridge/exchange.go [hunk 8]
```diff
@@ -0,0 +1,161 @@
...
+const (
+	ExchangeBridgeServiceName = "aws.firecracker.containerd.exchangeBridge"
+	GetEventMethodName = "GetEvent"
+)
+
+// The ExchangeBridge interface provides an API for retrieving containerd events from a remote event exchange. It exists
+// separately from containerd's existing EventClient and EventServer interfaces in order to support retrieving events
+// via long-polling as opposed to a streaming model. This allows us to use TTRPC for the implementation, which currently
+// does not support streaming.
+type ExchangeBridge interface {
```
Comment (xibz) [inline exchangeBridge/exchange.go]: I am curious if it makes some sense to expose `ExchangeBridgeService` and pass in a `EventListener` during creation. Need a better name I think for the `EventListener.

```go
type EventListener interface {
    GetEvent(ctx context.Context) (*eventapi.Envelope, error)
}

type TTRPCEventListener struct {
    // stuff
}

func NewExchangeBridgeService(ctx context.Context, eventSource events.Subscriber, e EventListener) {
}
```

Then you can have a `TTRPCEventListener`. This allows reuse of the of some of the code and allows switching out of how the events are retrieved. What are your thoughts on that?

File: exchangeBridge/exchange.go (hunk 5 above)
Comment (xibz) [inline exchangeBridge/exchange.go]: And can you move this down after the method. I tend to group methods with the structure it is tied to.

Comment (sipsma) [reply exchangeBridge/exchange.go]: Sure, will do

File: exchangeBridge/exchange.go (hunk 7 above)
Comment (sipsma) [reply exchangeBridge/exchange.go]: Sure, will do

**Comment by sipsma** [comment]
> Can we also get some tests to ensure this works properly?

Yes, mentioned this in the PR description but I don't plan on merging this until I've gotten an integration test up and running, which may take a few days. Just getting any feedback on the implementation out of the way first.

File: agent/main.go [hunk 9]
```diff
@@ -71,7 +65,7 @@ func main() {
 	signals := make(chan os.Signal, 32)
 	signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM, unix.SIGCHLD)
 
-	ctx, cancel := context.WithCancel(context.Background())
+	ctx, cancel := context.WithCancel(namespaces.WithNamespace(context.Background(), defaultNamespace))
```
[the remark this answers is not in the document]
Comment (sipsma) [reply agent/main.go]: Created an issue for that here: https://github.com/firecracker-microvm/firecracker-containerd/issues/119

Let me know if the labeling is correctly following our conventions

File: exchangeBridge/exchange.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (sipsma) [reply exchangeBridge/exchange.go]: I ended up doing something else entirely. The package is "eventbridge" and I changed the service name to just "Getter" (reflecting that all it does is GetEvent over the eventbridge). I think this is the best compromise.

File: eventbridge/eventbridge.go [hunk 10]
```diff
@@ -0,0 +1,173 @@
...
+			Topic:     receivedEnvelope.Topic,
+			Event:     receivedEnvelope.Event,
+		}, nil
+	case err := <-s.errChan:
+		return nil, err
+	case <-ctx.Done():
+		if ctxErr := ctx.Err(); ctxErr != context.Canceled {
+			return nil, ctxErr
+		}
+		return nil, nil
```
Comment (mxpv) [inline eventbridge/eventbridge.go]: I would rather return an error and make client responsible whether he wants to ignore `context.Canceled`.
When `GetEvent` returns `nil` error I expect that I can use envelope safely. Or at least this should be mentioned in godoc.

Comment (sipsma) [reply eventbridge/eventbridge.go]: Yeah I see your point, I went back and forth on this a bit. My original reasoning was that because the caller is providing context, they can be aware if it's canceled just as easily as the callee and thus shouldn't be forced to always check `if err != context.Canceled`. Err should just indicate that something went wrong with the callee's logic specifically.

However, you make a good a point that its pretty standard to assume that if err is nil you can go ahead and use the primary return value(s). Given that's a much more common assumption and doesn't change anything functionally, I'll switch to what you're suggesting.

File: eventbridge/eventbridge.go [hunk 11]
```diff
@@ -0,0 +1,173 @@
...
+		select {
+		case <-ctx.Done():
+			if ctxErr := ctx.Err(); ctxErr != context.Canceled {
+				return ctxErr
+			}
+			return nil
+		default:
+		}
+
+		envelope, err := source.GetEvent(ctx)
```
Comment (xibz) [inline eventbridge/eventbridge.go]: I have a concern with this loop just spinning since it makes the assumption that `GetEvent` will handle not spinning this loop. I think another method of `HasEvent` or something of that nature needs to be added and should behave similarly to how `ctx.Done` works by returning a channel.

Comment (sipsma) [reply eventbridge/eventbridge.go]: The Godoc for getterClient.GetEvent mentions that it's blocking, I can add an additional short comment above the line your commenting on re-iterating it.

Comment (xibz) [reply eventbridge/eventbridge.go]: I think this needs to be added to the interface's method signature of `GetEvent`. There is no mention of that in the interface.

Comment (sipsma) [reply eventbridge/eventbridge.go]: Yeah I just noticed that too, I am adding a comment to the interface method too in addition to the implementations.

**Comment by mxpv** [comment]
Ref https://github.com/firecracker-microvm/firecracker-containerd/issues/24

**Comment by sipsma** [comment]
Updated w/ unit tests. I also have an e2e test written in my fork of the repo, will update this PR with it once I have merged the prerequisite #134

**Comment by sipsma** [comment]
I updated w/ the e2e test. It's a pretty sizable change on top of the original so it's a separate commit.

The travis build is exiting with non-zero for reasons unknown to me at this time. When I run "make lint" on my own from the same commit it exits with 0.

**Comment by sipsma** [comment]
The travis build was failing due to it only pulling 50 commits of history, which broke our git validation command. 

Sam fixed this, I will pick up that fix when I squash/rebase before merging. `make lint` passes locally though for these changes.

File: go.mod [hunk 12]
```diff
@@ -1,8 +1,10 @@
 module github.com/firecracker-microvm/firecracker-containerd
 
 require (
+	github.com/BurntSushi/toml v0.3.1 // indirect
 	github.com/Microsoft/go-winio v0.4.11 // indirect
 	github.com/Microsoft/hcsshim v0.8.1 // indirect
+	github.com/StackExchange/wmi v0.0.0-20181212234831-e0a55b97c705 // indirect
```
Comment (samuelkarp) [inline go.mod]: Is this being pulled in by containerd?

Comment (sipsma) [reply go.mod]:
```
go mod why github.com/StackExchange/wmi      
                                                                                                                                                                                                                                                                                                                           
# github.com/StackExchange/wmi
github.com/firecracker-microvm/firecracker-containerd/internal
github.com/shirou/gopsutil/process
github.com/StackExchange/wmi
```

It appears to be the psutil library needed by the new service_integ_test package. That library also supports windows, so it makes sense I guess.

File: .buildkite/pipeline.yml [hunk 13]
```diff
@@ -61,21 +63,43 @@ steps:
...
 
-  - label: ":running_shirt_with_sash: runtime tests"
+  - label: ":exclamation: event tests"
+    command:
+      >
+        docker run --rm \
+          localhost/firecracker-containerd-unittest-nonroot:${BUILDKITE_BUILD_NUMBER} \
+          '
+            cd /firecracker-containerd/eventbridge
+            go test . -v -count=1
```
[the remark this answers is not in the document]
Comment (sipsma) [reply .buildkite/pipeline.yml]: Done

File: .buildkite/pipeline.yml [hunk 14]
```diff
@@ -61,21 +63,43 @@ steps:
             DISABLE_ROOT_TESTS='true' make test EXTRAGOARGS="-v -count=1"
           '
 
-  - label: ":running_shirt_with_sash: runtime tests"
+  - label: ":exclamation: event tests"
+    command:
```
[the remark this answers is not in the document]
Comment (sipsma) [reply .buildkite/pipeline.yml]: Done

File: agent/main.go [hunk 15]
```diff
@@ -32,26 +33,19 @@ import (
...
 	"golang.org/x/sync/errgroup"
 	"golang.org/x/sys/unix"
+
+	"github.com/firecracker-microvm/firecracker-containerd/eventbridge"
 )
 
 const (
-	defaultPort = 10789
+	defaultPort      = 10789
+	defaultNamespace = "default"
```
Comment (samuelkarp) [inline agent/main.go]: This is defined in `namespaces.Default`.

Comment (sipsma) [reply agent/main.go]: Fixed while squashing commits
