### PR TITLE
Don't patch non-stub drives

### LINKED ISSUE #230: Cannot reuse a Firecracker VM from multiple containers without specifying Container Count
(From #225)

Probably due to the way we handle stub drives, re-using a Firecracker VM from multiple containers doesn't work due to a mysterious

> Drive "root_drive" could not be found

error.

### PR DESCRIPTION
**Pull request by kzys**
*Issue #, if available:*

Related to, but may need more changes to actually fix #230

*Description of changes:*

Currently the drive handler knows non-stub drives (root drive). Because of that PatchStubDrive() replace non-stub drives, once all stub drives are patched.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kzys** [comment]
Honestly speaking, I'm unsure this is the right place to address the issue. We could argue that the drive handler shouldn't know about a root drive and the caller of this handler should not pass the root drive.

File: runtime/drive_handler.go [hunk 1]
```diff
@@ -125,10 +125,20 @@ func (h *stubDriveHandler) createStubDrive(driveID, path string) error {
 	return nil
 }
 
+func filterOnlyStubDrives(drives []models.Drive) []models.Drive {
```
Comment (xibz) [inline runtime/drive_handler.go]: Let's move this function out of drive handler and into the `service.go`. You can then call the method before [set drives](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/runtime/service.go#L651).

Comment (xibz) [inline runtime/drive_handler.go]: May be a good idea to document why this occurs which is due to the root drive being always being the last element when `Build` is called on the drive builder from the SDK.

File: runtime/drive_handler.go [hunk 2]
```diff
@@ -125,10 +125,20 @@ func (h *stubDriveHandler) createStubDrive(driveID, path string) error {
...
+		if !*d.IsRootDevice {
+			stubDrives = append(stubDrives, d)
+		}
+	}
+	return stubDrives
+}
+
 // SetDrives will set the given drives and the offset to which the stub drives
 // start.
 func (h *stubDriveHandler) SetDrives(offset int64, d []models.Drive) {
```
Comment (xibz) [inline runtime/drive_handler.go]: This offset can be removed all together with the function provided above.

File: runtime/drive_handler.go [hunk 3]
```diff
@@ -125,10 +125,20 @@ func (h *stubDriveHandler) createStubDrive(driveID, path string) error {
 	return nil
 }
 
+func filterOnlyStubDrives(drives []models.Drive) []models.Drive {
+	stubDrives := make([]models.Drive, 0)
```
Comment (mxpv) [inline runtime/drive_handler.go]: nit: I'd rather prefer preallocating here as we know the size in advance: `make([]models.Drive, 0, len(drives))`

File: runtime/drive_handler.go (hunk 1 above)
Comment (kzys) [reply runtime/drive_handler.go]: You meant, this `Build`.

https://github.com/firecracker-microvm/firecracker-go-sdk/blob/29621e288fa1333809e5b43d867dbb73d82b5456/drives.go#L63

BTW, why do we want to place the root drive at the end?

File: runtime/drive_handler.go (hunk 3 above)
Comment (kzys) [reply runtime/drive_handler.go]: Wouldn't it allocate more than what we need?

File: runtime/drive_handler.go (hunk 1 above)
Comment (xibz) [reply runtime/drive_handler.go]: The location of root drive is arbitrary. End was chosen since you didn't need to create a `[]models.Drive` to append to.

**Comment by xibz** [comment]
I wonder if it makes sense to just have an array of stub drives that is passed into `SetDrives`. We only use a single drive builder, but it doesn't mean we can use two. That may simpler than trying to filter, and if we prefer filtering we may want to filter on what is a stub drive as opposed to what is root.

**Comment by kzys** [comment]
It does make sense. `runtime/service.go` knows about stub drives, but Firecracker doesn't have the notion of stub drives. Thus fiding stub-drives on Firecracker-origin structs (such as cfg.Drives) is not straightforward.

File: runtime/drive_handler.go [hunk 4]
```diff
@@ -125,10 +125,20 @@ func (h *stubDriveHandler) createStubDrive(driveID, path string) error {
...
+		}
+	}
+	return stubDrives
+}
+
 // SetDrives will set the given drives and the offset to which the stub drives
 // start.
 func (h *stubDriveHandler) SetDrives(offset int64, d []models.Drive) {
-	h.drives = d
+	h.drives = filterOnlyStubDrives(d)
```
Comment (sipsma) [inline runtime/drive_handler.go]: What's the error now when you encounter the issue in #230 ?

The fix here is good either way and if the error is still unclear that can be addressed separately, just curious if it's changed to something more comprehensible.

File: runtime/drive_handler.go (hunk 3 above)
Comment (mxpv) [reply runtime/drive_handler.go]: Should it be just `make([]models.Drive)` then?

File: runtime/drive_handler.go (hunk 4 above)
Comment (kzys) [reply runtime/drive_handler.go]: Good point. Let me try that.

File: runtime/drive_handler.go (hunk 1 above)
Comment (kzys) [reply runtime/drive_handler.go]: While the latest version doesn't have filterOnlyStubDrives() anymore (as @xibz suggested), all changes are in service.go now.

Comment (kzys) [reply runtime/drive_handler.go]: Thanks. The new revision has some comments around drives initialization. Would it be good enough?

File: runtime/drive_handler.go (hunk 2 above)
Comment (kzys) [reply runtime/drive_handler.go]: Now offset is always zero. I will remove the parameter later.

File: runtime/drive_handler.go (hunk 3 above)
Comment (kzys) [reply runtime/drive_handler.go]: We don't have the filter logic anymore, and all `make` calls explicitly specify the capacity.

File: runtime/drive_handler.go (hunk 4 above)
Comment (kzys) [reply runtime/drive_handler.go]: Now the error mentions "failed to patch stub drive: There are no remaining drives to be used" which is better than what I had before

```
--- FAIL: TestCreateContainerWithSameName_Isolated (33.06s)
    require.go:794:
                Error Trace:    service_integ_test.go:565
                                                        service_integ_test.go:655
                                                        service_integ_test.go:676
                Error:          Received unexpected error:
                                unknown
                                github.com/containerd/containerd/errdefs.init.ializers
                                        /go/pkg/mod/github.com/containerd/containerd@v1.2.1-0.20190711201753-f2b6c31d0fa7/errdefs/errors.go:43
                                runtime.main
                                        /usr/local/go/src/runtime/proc.go:188
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1337
                                failed to patch stub drive: There are no remaining drives to be used
                                github.com/containerd/containerd/errdefs.FromGRPC
                                        /go/pkg/mod/github.com/containerd/containerd@v1.2.1-0.20190711201753-f2b6c31d0fa7/errdefs/grpc.go:107
                                github.com/containerd/containerd.(*container).NewTask
                                        /go/pkg/mod/github.com/containerd/containerd@v1.2.1-0.20190711201753-f2b6c31d0fa7/container.go:286
                                github.com/firecracker-microvm/firecracker-containerd/runtime.startAndWaitTask
                                        /firecracker-containerd/runtime/service_integ_test.go:564
                                github.com/firecracker-microvm/firecracker-containerd/runtime.testCreateContainerWithSameName
                                        /firecracker-containerd/runtime/service_integ_test.go:655
                                github.com/firecracker-microvm/firecracker-containerd/runtime.TestCreateContainerWithSameName_Isolated
                                        /firecracker-containerd/runtime/service_integ_test.go:676
                                testing.tRunner
                                        /usr/local/go/src/testing/testing.go:865
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1337
                Test:           TestCreateContainerWithSameName_Isolated
                Messages:       failed to create task for container TestCreateContainerWithSameName_Isolated-1565126341850109350
FAIL
exit status 1
```

Comment (sipsma) [reply runtime/drive_handler.go]: Nice, yeah that's much clearer than before
